# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NGViZTMwNmJhZTY1N2FkNmYwY2E2ZDY2NWNjMzA3MmQyNzE3YzYxMjZiZmMzMjgwMzczMTJhZWE4MjdkMWEyN2U1Nzc2N2Y4OGI0ZWEwOGFlZTliYjkzNzFhMTBiM2ZiNDAyMWViMWUxYThiMzlmODdlMmNhMzNhMDE2NTk5MzA=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
